{% set name = "autodoc-pydantic" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autodoc_pydantic-{{ version }}.tar.gz
  sha256: f24a2f2098f5c121112cde18930ee318e4bc33893939eca14d764d09c2fbd95c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - pydantic >=1.5
    - python >=3.6,<4.0
    - sphinx >=3.4

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.autodoc_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mansenfranzen/autodoc_pydantic
  doc_url: https://autodoc-pydantic.readthedocs.io/en/latest/
  summary: Seamlessly integrate pydantic models in your Sphinx documentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
