{% set name = "autodoc-pydantic" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autodoc_pydantic-{{ version }}.tar.gz
  sha256: 7a125a4ff18e4903e27be71e4ddb3269380860eacab4a584d6cc2e212fa96991

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.1,<4.0
    - poetry
  run:
    - pydantic >=1.5,<2.0.0
    - python >=3.7.1,<4.0
    - sphinx >=3.4

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.autodoc_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mansenfranzen/autodoc_pydantic
  doc_url: https://autodoc-pydantic.readthedocs.io/en/latest/
  summary: Seamlessly integrate pydantic models in your Sphinx documentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
