{% set name = "autodoc-pydantic" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autodoc_pydantic-{{ version }}.tar.gz
  sha256: 82aad0ea4a49efd6446dc9001d74d13d908138b846d3eacd524821bce2671da2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - pydantic >=1.5
    - python >=3.6,<4.0
    - sphinx >=3.4

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.autodoc_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mansenfranzen/autodoc_pydantic
  doc_url: https://autodoc-pydantic.readthedocs.io/en/latest/
  summary: Seamlessly integrate pydantic models in your Sphinx documentation.
  description: |
    You love [pydantic](https://pydantic-docs.helpmanual.io/) ❤ and you want to
    document your models and configuration settings with [sphinx](https://www.sphinx-doc.org/en/master/)?

    Perfect, let's go. But wait, sphinx' [autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html)
    does not integrate too well with pydantic models 😕.

    Don't worry - just `pip install autodoc_pydantic` ☺.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
