{% set name = "autodoc-pydantic" %}
{% set version = "1.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autodoc_pydantic-{{ version }}.tar.gz
  sha256: 1b987b66ef92212ea4743cae880000a24d1334d63358a3e505a6c925780248f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - pydantic >=1.5
    - python >=3.6,<4.0
    - sphinx >=3.4

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.autodoc_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mansenfranzen/autodoc_pydantic
  doc_url: https://autodoc-pydantic.readthedocs.io/en/latest/
  summary: Seamlessly integrate pydantic models in your Sphinx documentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
